version: '2'
services:
  redisintegrationjhi-app:
    image: redisintegrationjhi
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - JHIPSTER_CACHE_REDIS_SERVER=redis://redisintegrationjhi-redis:6379
      - SPRING_DATA_CASSANDRA_CONTACTPOINTS=redisintegrationjhi-cassandra
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  redisintegrationjhi-cassandra:
    extends:
      file: cassandra-cluster.yml
      service: redisintegrationjhi-cassandra
  redisintegrationjhi-cassandra-node:
    image: cassandra:3.11.5
    environment:
      - CASSANDRA_SEEDS=redisintegrationjhi-cassandra
  redisintegrationjhi-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: redisintegrationjhi-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
  redisintegrationjhi-redis:
    extends:
      file: redis.yml
      service: redisintegrationjhi-redis
