version: '2'
services:
  redisintegrationjhi-app:
    image: redisintegrationjhi
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://redisintegrationjhi-mariadb:3306/redisintegrationjhi
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  redisintegrationjhi-mariadb:
    extends:
      file: mariadb.yml
      service: redisintegrationjhi-mariadb
